### ISSUE TITLE
additional maintainers

### ISSUE THREAD

**Issue by michaelglass** [michaelglass/rspec-retry#30]
Hey there! I think this gem is used by enough people to be helped by additional maintainers.  Thoughts? I volunteer myself but think the role would be better for folks who have actually worked on the gem / created PRs.  @y310 do you think you would be amenable to that?

**Comment by y310** [comment]
Yes, honestly I don't have enough time to maintain this gem and I don't use this by myself.
So anyone who wants to be an maintainer is welcome!

**Comment by michaelglass** [comment]
please add me as a contributor / gem pusher and I'll take up the responsibility, thanks!

**Comment by y310** [comment]
@michaelglass Thanks! I added you to collaborator. could you let me know your rubygems account?

**Comment by michaelglass** [comment]
me@mike.is

**Comment by y310** [comment]
Added you to rubygems owner.
You can do anything you want. no need to ask me :+1:

**Comment by michaelglass** [comment]
can you give me admin access to this repo so I can set up travis?

**Comment by michaelglass** [comment]
and/or I'd move the canonical repo to /michaelglass or /noredink, either way.

**Comment by y310** [comment]
According to [this document](https://help.github.com/articles/permission-levels-for-a-user-account-repository/), owner permission can be assigned to only one user.
ok, so let's transfer to your account. I think `/noredink` is better because it's organization.

Maybe, you need to delete existing `/noredink/rspec-retry`, right?

> Before you transfer a repository, keep these things in mind:
> The target account must not have a repository with the same name, or a fork in the same network.

ref: https://help.github.com/articles/transferring-a-repository/

**Comment by michaelglass** [comment]
deleted /noredink/rspec-retry

**Comment by y310** [comment]
oops... 
![image](https://cloud.githubusercontent.com/assets/188655/8614782/69293088-26ed-11e5-8a5e-44b7bf68f840.png)

I'd like to transfer to `/michaelglass` at first.
could you remove '/michaelglass/rspec-retry`?

**Comment by michaelglass** [comment]
deleted

**Comment by y310** [comment]
done. please confirm transfer request

**Comment by michaelglass** [comment]
I don't think that worked...

**Comment by y310** [comment]
oh weird.. in my screen, it was correctly transferred.
![image](https://cloud.githubusercontent.com/assets/188655/8616046/5b9f6f4e-26f8-11e5-84b9-4ba98de4b332.png)

**Comment by michaelglass** [comment]
maybe it will take some time? We'll see

**Comment by michaelglass** [comment]
thanks, @y310
